name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: 22
        script: |
          # Создание директорий если не существуют
          sudo mkdir -p /var/www/beresta
          sudo chown $USER:$USER /var/www/beresta
          
          # Переход в директорию проекта
          cd /var/www/beresta
          
          # Клонирование репозитория если не существует
          if [ ! -d ".git" ]; then
            echo "Cloning repository..."
            git clone https://github.com/${{ github.repository }}.git .
          fi
          
          # Обновление кода
          echo "Updating code..."
          git fetch origin
          git reset --hard origin/main
          
          # Создание необходимых директорий
          mkdir -p app/data logs ssl
          
          # Создание самоподписанного SSL сертификата если не существует
          if [ ! -f ssl/beresta.crt ] || [ ! -f ssl/beresta.key ]; then
            echo "Creating self-signed SSL certificate..."
            sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
              -keyout ssl/beresta.key \
              -out ssl/beresta.crt \
              -subj "/C=RU/ST=Saratov/L=Saratov/O=Beresta/CN=beresta.one"
            sudo chown $USER:$USER ssl/*
          fi
          
          # Копирование production конфигурации с правильным именем образа
          sed "s/your-username\/beresta-website/${{ github.repository }}/g" docker-compose.prod.yml > docker-compose.yml
          
          # Остановка текущих контейнеров
          echo "Stopping current containers..."
          docker-compose down || true
          
          # Сборка нового образа
          echo "Building new image..."
          docker-compose build --no-cache beresta-app
          
          # Запуск обновленных контейнеров
          echo "Starting updated containers..."
          docker-compose up -d beresta-app
          
          # Очистка старых образов
          echo "Cleaning up old images..."
          docker image prune -f
          
          echo "Deployment completed successfully!"

    - name: Health check
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: 22
        script: |
          # Проверка статуса контейнеров
          docker-compose ps
          
          # Проверка доступности сайта
          curl -f https://beresta.one/ || exit 1
          curl -f https://beresta.one/applications/ || exit 1
          
          echo "Health check passed!"

    - name: Notify deployment status
      if: always()
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: 22
        script: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful!"
            echo "🌐 Site: https://beresta.one"
            echo "📱 App: https://beresta.one/app"
          else
            echo "❌ Deployment failed!"
            echo "Check logs for details"
          fi